jenkins:
  # Stricter agent to master trust model per:
  # https://wiki.jenkins.io/display/JENKINS/Slave+To+Master+Access+Control
  remotingSecurity:
    enabled: true

  # Enable CSRF protection
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
